#!/usr/bin/env node

/**
 * VitaBlog Initialization Script
 * This script helps set up your blog for the first time
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

async function init() {
  console.log('\n🚀 VitaBlog Initialization\n');
  console.log('This script will help you set up your blog.\n');

  // Check if .env exists
  const envPath = path.join(__dirname, '.env');
  if (fs.existsSync(envPath)) {
    const overwrite = await question('⚠️  .env file already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('✅ Keeping existing .env file');
      rl.close();
      return;
    }
  }

  console.log('\n📝 Database Configuration:');
  const dbName = await question('Database name [vitablog]: ') || 'vitablog';
  const dbUser = await question('Database user [postgres]: ') || 'postgres';
  const dbPassword = await question('Database password: ');
  const dbHost = await question('Database host [localhost]: ') || 'localhost';
  const dbPort = await question('Database port [5432]: ') || '5432';

  console.log('\n🔐 Security Configuration:');
  const jwtSecret = await question('JWT Secret (press Enter for random): ') || 
    require('crypto').randomBytes(32).toString('hex');

  console.log('\n🌐 Server Configuration:');
  const port = await question('Server port [5001]: ') || '5001';
  const clientUrl = await question(`Client URL [http://localhost:${port}]: `) || `http://localhost:${port}`;

  // Create .env file
  const envContent = `# VitaBlog Environment Configuration
# Generated by init.js

NODE_ENV=development
PORT=${port}

# Database Configuration
DB_NAME=${dbName}
DB_USER=${dbUser}
DB_PASSWORD=${dbPassword}
DB_HOST=${dbHost}
DB_PORT=${dbPort}

# JWT Secret
JWT_SECRET=${jwtSecret}

# Client URL
CLIENT_URL=${clientUrl}
`;

  fs.writeFileSync(envPath, envContent);
  console.log('\n✅ .env file created successfully!');

  // Ask about seeding
  const seed = await question('\n🌱 Would you like to seed the database with sample data? (Y/n): ');
  if (seed.toLowerCase() !== 'n') {
    console.log('\n📦 Running database seed...');
    try {
      require('./scripts/seed.js');
      console.log('\n✅ Database seeded!');
    } catch (error) {
      console.error('\n❌ Seeding failed. You can run it manually later:');
      console.error('   node scripts/seed.js');
    }
  }

  console.log('\n🎉 Setup complete!');
  console.log('\n📋 Next steps:');
  console.log('   1. Make sure PostgreSQL is running');
  console.log('   2. Start the server: npm run server:dev');
  console.log('   3. Open http://localhost:' + port + ' in your browser');
  console.log('\n📝 Default accounts (if seeded):');
  console.log('   Admin: admin@vitablog.co / admin123');
  console.log('   Author: author@vitablog.co / author123');
  console.log('\n');

  rl.close();
}

init().catch(error => {
  console.error('❌ Initialization failed:', error);
  rl.close();
  process.exit(1);
});

